# Конфиг для Netlify, который позволяет обрабатывать все запросы
# через index.html, что необходимо для SPA-приложений
[[redirects]]
# Все запросы перенаправляем на index.html
  from = "/*"
  to = "/index.html"
  status = 200
